[project]
name = "canvalib"
version = "0.0.1"
authors = [
  { name="danb1551", email="danielbalcar22@gmail.com" },
]
description = "canva library for terminal"
readme = "README.md"
requires-python = ">=3.9"
requires-colorama = ">=0.4.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Natural Language :: Czech",
    "Topic :: Printing"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/danb1551/canvalib"
Issues = "https://github.com/danb1551/canvalib/issues"